### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/noxlaw/.local/lib/python3.8/site-packages/platinum/data\\android_dev.json'

### ISSUE THREAD

**Issue by lawbyte** [fjwCode/platinum#1]
>>> from platinum import Chromium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noxlaw/.local/lib/python3.8/site-packages/platinum/__init__.py", line 19, in <module>
    from .user_agent import generate_user_agent, InvalidOption
  File "/home/noxlaw/.local/lib/python3.8/site-packages/platinum/user_agent.py", line 15, in <module>
    from .constants import *
  File "/home/noxlaw/.local/lib/python3.8/site-packages/platinum/constants.py", line 300, in <module>
    open(os.path.join(PACKAGE_DIR, 'data\\android_dev.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/home/noxlaw/.local/lib/python3.8/site-packages/platinum/data\\android_dev.json'

**Comment by itzcodex24** [comment]
Experiencing the same issue today, any fixes?
